version: "3.9"

services:
  database:
    image: postgres:17.2-alpine
    container_name: db-init-new
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-usr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set in .env}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - app
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: java-api/Dockerfile
    container_name: simpleapi-new
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app
    restart: unless-stopped

  httpd:
    build:
      context: ./http-server   
      dockerfile: Dockerfile
    container_name: http-proxy-new
    ports:
      - "8089:80"             
    depends_on:
      - backend
    networks:
      - app
    restart: unless-stopped

networks:
  app: {}

volumes:
  pgdata: {}
