#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/net
- name: Ensure app<->db network exists
  community.docker.docker_network:
    name: app_network
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Ensure app<->proxy network exists
  community.docker.docker_network:
    name: proxy_network
    state: present  
  vars:
    ansible_python_interpreter: /usr/bin/python3