name: CD

on:
  workflow_run:
    workflows: ["CI"]       
    types: [completed]
  push:
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible community.docker

      - name: Add host to known_hosts
        if: ${{ secrets.SSH_KNOWN_HOSTS == '' }}
        run: |
          ssh-keyscan ${{ secrets.TARGET_HOST }} >> ~/.ssh/known_hosts

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible --version
          ansible-playbook -i inventories/setup.yml playbook.yml \
            -e "ansible_user=${{ secrets.TARGET_USER }}"
