name: CI devops 2025

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  # ---- CI job ----
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # Checkout du code
      - uses: actions/checkout@v4

      # Installation du JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Build et tests Maven
      - name: Build and test with Maven
        working-directory: "./TP - Part 1/java-api/simpleapi"
        run: mvn -B clean verify


  # ---- CD job ----
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: "./TP - Part 1/java-api"
          file: "./TP - Part 1/java-api/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: "./TP - Part 1"
          file: "./TP - Part 1/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: "./TP - Part 1/http-server"
          file: "./TP - Part 1/http-server/Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
