name: CI devops 2025
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
    #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      
      - name: Show folder structure
        run: ls -R
      #finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: "./TP - Part 1 /java-api/simpleapi"
        run: mvn -B clean verify
